### ISSUE TITLE
inline-python-macros not found on python 3.11

### ISSUE THREAD

**Issue by gauteh** [fusion-engineering/inline-python#63]
The error below appears when I use python=3.11, but not when using 3.10. Python installed via mamba + conda-forge.

```
❯ cat environment.yml
name: acoustics
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
```

Regards, Gaute

---

Hi,

I am currently getting an error:

```
error[E0463]: can't find crate for `inline_python_macros`
   --> /home/gauteh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/inline-python-0.12.0/src/lib.rs:138:9
    |
138 | pub use inline_python_macros::python;
    |         ^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `inline-python` (lib) due to previous error

```

with the latest three nightly versions (back to and including 2023-07-22). With 2023-06-28 I am getting a bunch of:

```
   Compiling inline-python-macros v0.12.0
error[E0599]: no method named `line` found for struct `proc_macro::Span` in the current scope
  --> /home/gauteh/.cargo/registry/src/index.crates.io-6f17d22bba15001f/inline-python-macros-0.12.0/src/embed_python.rs:57:35
   |
57 |             self.add_whitespace(span, span.line(), span.column())?;
   |                                            ^^^^ method not found in `Span`


```

_Originally posted by @gauteh in https://github.com/fusion-engineering/inline-python/issues/62#issuecomment-1658195742_

**Comment by gauteh** [comment]
Also does not work on python 3.14.

**Comment by m-ou-se** [comment]
Looks like you're using an outdated version of Rust.

**Comment by gauteh** [comment]
Tried both latest stable and nightly. Machine was brand new Ubuntu vm with rust through rustup. Can try some more later.

**Comment by gauteh** [comment]
```
❯ git clone https://github.com/m-ou-se/inline-python.git
Cloning into 'inline-python'...
remote: Enumerating objects: 1012, done.
remote: Counting objects: 100% (439/439), done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 1012 (delta 241), reused 371 (delta 198), pack-reused 573 (from 1)
Receiving objects: 100% (1012/1012), 150.30 KiB | 2.21 MiB/s, done.
Resolving deltas: 100% (481/481), done.
gauteh in 🌐 gauteh in ~/dev
❯ cd inline-python
gauteh in 🌐 gauteh in inline-python on  master via 🦀 v1.95.0
❯ ll
total 32K
-rw-rw-r-- 1 gauteh gauteh  523 May  5 14:38 Cargo.toml
drwxrwxr-x 4 gauteh gauteh 4.0K May  5 14:38 ct-python
drwxrwxr-x 2 gauteh gauteh 4.0K May  5 14:38 examples
-rw-rw-r-- 1 gauteh gauteh 1.4K May  5 14:38 LICENSE
drwxrwxr-x 3 gauteh gauteh 4.0K May  5 14:38 macros
-rw-rw-r-- 1 gauteh gauteh 2.9K May  5 14:38 README.md
drwxrwxr-x 2 gauteh gauteh 4.0K May  5 14:38 src
drwxrwxr-x 2 gauteh gauteh 4.0K May  5 14:38 tests
gauteh in 🌐 gauteh in inline-python on  master via 🦀 v1.95.0
❯ cargo test
warning: `/home/gauteh/.cargo/config` is deprecated in favor of `config.toml`
  |
  = help: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Updating crates.io index
     Locking 19 packages to latest Rust 1.88.0 compatible versions
      Adding pyo3 v0.25.1 (available: v0.28.3)
  Downloaded target-lexicon v0.13.5
  Downloaded once_cell v1.21.4
  Downloaded libc v0.2.186
  Downloaded 3 crates (863.1KiB) in 0.19s
   Compiling target-lexicon v0.13.5
   Compiling once_cell v1.21.4
   Compiling libc v0.2.186
   Compiling autocfg v1.5.0
   Compiling memoffset v0.9.1
   Compiling pyo3-build-config v0.25.1
   Compiling pyo3-ffi v0.25.1
   Compiling pyo3 v0.25.1
   Compiling inline-python-macros v0.16.1 (/home/gauteh/dev/inline-python/macros)
   Compiling inline-python v0.14.4 (/home/gauteh/dev/inline-python)
error[E0463]: can't find crate for `inline_python_macros`
   --> src/lib.rs:141:9
    |
141 | pub use inline_python_macros::python;
    |         ^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `inline-python` (lib test) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `inline-python` (lib) due to 1 previous error
gauteh in 🌐 gauteh in inline-python on  master via 🦀 v1.95.0 took 7s
❯ rustc --version
rustc 1.95.0 (59807616e 2026-04-14)
gauteh in 🌐 gauteh in inline-python on  master via 🦀 v1.95.0
❯ python --version
Python 3.13.13
gauteh in 🌐 gauteh in inline-python on  master via 🦀 v1.95.0
❯
``` 

Ran this on a fresh clone of this repository. Python is from conda-forge.

**Comment by gauteh** [comment]
Using py 3.10 doesn't seem to make any difference.

**Comment by gauteh** [comment]
Adding: ` export LD_LIBRARY_PATH=/home/gauteh/.mconda3/lib` fixed it. Using `extern crate` gave a much more helpful error message, can't find libpython.

**Comment by gauteh** [comment]
https://github.com/PyO3/pyo3/issues/1554 and http://github.com/PyO3/pyo3/issues/4155

**Comment by de-vri-es** [comment]
Seems like the dynamic loader fails to load the proc macro crate because it links against libpython, which wasn't found. So the real problem is a bad error message from the compiler.

However:

> Using `extern crate` gave a much more helpful error message, can't find libpython.

Which `extern crate`, and Where did you put this exactly? And do you have an example of the error message with and without?

Because if it improves the error message we can just add it.

**Comment by gauteh** [comment]
Hi,

I added:

```
extern crate inline_python_macros;
```

before this line:

 https://github.com/m-ou-se/inline-python/blob/master/src/lib.rs#L141

Gaute
